plugins {
    id 'com.android.application' version '7.4.2'
    id 'org.jetbrains.kotlin.android' version '1.8.22'
}

android {
    namespace 'com.example.safeerbrowser'
    compileSdk 34
    buildToolsVersion '34.0.0'

    defaultConfig {
        applicationId 'com.example.safeerbrowser'
        minSdk 28
        targetSdk 34
        versionCode 187
        versionName '2.1.78'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src/main/kotlin']
            kotlin.srcDirs = ['src/main/kotlin']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ['-opt-in=androidx.media3.common.util.UnstableApi']
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig null
        }
        debug {
            minifyEnabled false
            signingConfig null
        }
    }

    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/*.kotlin_module'
    }
}

dependencies {
    implementation 'androidx.media3:media3-exoplayer:1.4.1'
    implementation 'androidx.media3:media3-exoplayer-dash:1.4.1'
    implementation 'androidx.media3:media3-datasource:1.4.1'
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
