pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "tv-browser-2"
// Safeer OS: televizijska lupina na Safeer Linku (safeer-os/), isti podpisni kljuc kot brskalnik.
include ':safeer-os'
